name: 'Pull Request title rules'
description: 'Github action to enforce Pull Request title conventions'
author: 'deepakputhraya'
inputs:
  regex:
    description: 'Regex to validate the pull request title'
    required: false
    default: '.+'
  allowed_prefixes:
    description: 'Comma separated list of prefix allowed to be used in title. eg: feature,hotfix,JIRA-'
    required: false
    default: ''
  disallowed_prefixes:
    description: 'Comma separated list of prefix disallowed to be used in title. eg: feat,fix'
    required: false
    default: ''
  prefix_case_sensitive:
    description: 'Are the allowed & disallowed prefixes case sensitive?'
    required: false
    default: 'false'
  min_length:
    description: 'Min length of title'
    required: false
    default: '1'
  max_length:
    description: 'Max length of title. -1 to ignore the rule'
    required: false
    default: '-1'
  flags:
    description: "Regexp flags of the object."
    required: false
    default: ""
  help_message:
    description: "Help message displayed in the action execution logs to help the user understand how to correct the title of the Pull Request."
    required: false
    default: ""
  github_token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
    required: false
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
